name: BUILD AND PUSH

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
       
      - uses: docker/login-action@v2
      - name: Login to DockerHub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
      - name: Build the docker image
        run: docker build . --file Dockerfile --tag my-image/demo-github:$(date +%s)
        
      - name: Docker push
        run: docker push akshaya09082000/demo-github:latest
